server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # This default-filter is crucial. It adds the X-Forwarded headers
      # to every request that passes through the gateway.
      default-filters:
        - AddResponseHeader=X-Content-Type-Options, nosniff
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users/**

        - id: user-profile-service
          uri: lb://USER-PROFILE-SERVICE
          predicates:
            - Path=/api/profiles/**, /api/specialities/**, /api/doctors/**

        - id: consultation-service
          uri: lb://CONSULTATION-SERVICE
          predicates:
            - Path=/api/consultations/**

        - id: chat-service
          # The lb:ws:// scheme is critical for WebSocket load balancing
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**, /ws/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: your-super-secret-long-random-string-for-nidaan-pro

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE # Added for more detailed logging